### PR TITLE
Position calculation for `right` and `auto-right` when renderInPlace=true 

### LINKED ISSUE #255: horizontalPosition is ignored when you renderInPlace
setting `renderInPlace=true` and `horizontalPosition='right'` doesn't seem to put the content right-aligned but if `renderInPlace` is false then it is correctly aligned.

### PR DESCRIPTION
**Pull request by graemechapman**
Closes #255

### CODE REVIEW

**Comment by cibernox** [comment]
Sorry for delaying this so much. I'm going to test this now 👍

**Comment by cibernox** [comment]
@graemechapman can you rebase? I've improved the demo for the positioning to allow the user to toggle between in-place/wormhole. That will make the testing much easier.

**Comment by graemechapman** [comment]
@cibernox rebased :slightly_smiling_face:

**Comment by cibernox** [comment]
If you go to http://localhost:4200/docs/position you can play with all the combinations of positions, with and without `renderInPlace`. The behaviour with renderInPlace seems still broken.

**Comment by graemechapman** [comment]
> If you go to http://localhost:4200/docs/position you can play with all the combinations of positions, with and without renderInPlace. The behaviour with renderInPlace seems still broken.

Ah... I'll check it out, thanks!

**Comment by graemechapman** [comment]
@cibernox it's adding the right class names - I think the issue might be more to do with the css in the demo page? The in place dropdown gets a position of absolute, but there is no position on the parent so it is aligning to the body. Adding 
```css
    position: relative;
    display: inline-block;
```
to the `button-pull-left` element works - happy for me to include this?

**Comment by cibernox** [comment]
Ideally this should work automatically. It's hard to document that wherever they use this positioning with `renderInPlace=true` they must add certain classes to the parent div.
Perhaps the component could have a wrapper around both the trigger and the content when it's rendered in-place?

**Comment by cibernox** [comment]
After some experimentation I found that the demo was slightly broken because `renderInPlace` is not a property you're supposed to mutate, so the markup being rendered wasn't realistic.

Also, I think this PR is correct. This approach works in all cases except when the trigger is smaller than the full-width of the container on purpose. Since the user has to do that on purpose, I think it's also fair to force them to constraint the size of the wrapper on purpose.

**Comment by graemechapman** [comment]
Thanks @cibernox, yes I see that `renderInPlace` is referenced on init, makes sense that it needs a `tagName` for this to work 🙂

**Pull request merged**
