### PR TITLE
Run tests in headless chrome

### PR DESCRIPTION
**Pull request by cibernox**

### CODE REVIEW

**Comment by eriktrom** [comment]
yo @cibernox - chrome 59 is out - im about to try installing it for CI in our app, assuming it works, i'll copy the config back to this PR - if ur around ATM, let me know if was blocked for a reason other than waiting on chrome 59

**Comment by cibernox** [comment]
Actually the addon has been using headless chrome for a while. I forgot to close this

**Comment by eriktrom** [comment]
ahh - https://github.com/cibernox/ember-basic-dropdown/pull/310/files

`--window-size=1440,900` <-- so need that too, good to know, thanks for the testem.js issue link back to here :)

**Comment by cibernox** [comment]
It's only needed if you assert something related with the screen size, like positioning stuff. Most ppl don't need it

**Comment by eriktrom** [comment]
Gotcha. Valuable info. Thanks.

**Pull request closed without merging**
