### PR TITLE
Update ember-cli-sass

### PR DESCRIPTION
**Pull request by xomaczar**

### CODE REVIEW

**Comment by xomaczar** [comment]
Yeah I know, he did not check the latest code changes - I've raised that issue with the repo owner. What changed: support for node-sass 4.1.0 which now compiles on alphine linux - which ember-twiddle is running. So hopefully, we can use ember-basic-dropdown and ember-power-select with ember-twiddle.

**Comment by cibernox** [comment]
if you rebase this should be green too

**Comment by xomaczar** [comment]
Will do. Does ember-power-select suffers from the same issue?

**Comment by cibernox** [comment]
i fixed both

**Comment by xomaczar** [comment]
All green.

**Pull request merged**
