### PR TITLE
WIP: Positioning updates

### LINKED ISSUE #270: The position is not calculated properly when the dropdown is attached somewhere other than the body
This dropdown was placed in an element that was a child of the scrolling element so that it would scroll with the content. But the position was off because there was padding and margin not taken into account, and the viewportWidth was different. The positioning method assumes that the dropdown content is placed in the body element.

```hbs
<div class="scrollable-container">
  <div id="basic-dropdown-target-inside-scrollable-container">
  <!-- Blah blah blah content -->
    {{#basic-dropdown horizontalPosition="right" as |dropdown|}}
      {{#dropdown.trigger}}Click me{{/dropdown.trigger}}
      {{#dropdown.content to="basic-dropdown-target-inside-scrollable-container"}}
         ...
      {{/dropdown.content}}
    {{/basic-dropdown}}
  </div>
</div>
```

position dropdown inside scroll parent

### PR DESCRIPTION
**Pull request by RustyToms**
closes #270 

Adds the `targetContainerID` property to the basic-dropdown. This `targetContainerID` is used to change where the dropdown content is located using ember-wormhole.

The positioning logic is updated to account for the position and width of the new containing element.

### CODE REVIEW

**Comment by RustyToms** [comment]
@cibernox there is still more to do for this PR, and I still need to create examples, as you requested. But I wanted to post this so you could see what I was doing.

I am largely testing by modifying my fork and including it in my app, which has some of the more complicated situations. The positioning problem was a blocker, and so I wanted to fix it first.

**Comment by RustyToms** [comment]
```hbs
<div id="dropdown-target">
...
{{#basic-dropdown
  horizontalPosition="right"
  targetContainerID="dropdown-target"
  as |dropdown| }}
  {{#dropdown.trigger classNameBindings=":helix-dropdown dropdown.isOpen:open"}}
    <label class="helix-dropdown__options-label ttable__options-label {{if dropdown.isOpen "helix-dropdown__toggler--open"}}">
      <i class="fa fa-cog helix-dropdown__options-cog"></i>
    </label>
  {{/dropdown.trigger}}
  {{#dropdown.content}}
    stuff here
  {{/dropdown.content}}
{{/basic-dropdown}}
...
</div>
```
position_working

**Comment by cibernox** [comment]
Could you create a demo in the dummy app reproducing the problem before? I'd like to play myself with this problem a bit before agreeing on this solution, although I do think it's on the good direction.

**Comment by RustyToms** [comment]
@cibernox don't worry, don't feel pressured to accept this PR unless you like it.

I can't get the dummy app to build. I am just running `yarn install` and `ember serve`. When I tried to `yarn install` it gave me an error for `ember-native-dom-helpers`, same for `yarn check`. I think the lockfile was built with an older version of yarn. I am using 0.23.2. So I did `yarn upgrade` and was able to get it to finish, but then `yarn check` reported a ton of errors. The app built and loaded, but nothing was shown, and the dev console just reported a single error `regeneratorRuntime is not defined`. I assume the dependencies didn't load properly. I tried reinstalling a few times, even deleting the `node_modules` folder. I was able to run `npm install` without a problem, but same result.

Would you mind either updating the dependencies, or providing some instructions on building the dummy app? Maybe you can remove some dependencies? The `node_modules` folder ended up being 564 MB with yarn and 825 MB with npm, the complicated production app I am working on is 196 MB.

**Comment by cibernox** [comment]
I'll rebuid the yarn.lock. I had a problem locally due to offline caching.

**Comment by cibernox** [comment]
@RustyToms if rebase over master the yarn.lock should be correct now.

**Comment by RustyToms** [comment]
@cibernox I think you still need to push the changes up to master? I don't see any new commits

**Comment by cibernox** [comment]
I have indeed. Now it's fixed.

**Comment by RustyToms** [comment]
@cibernox do you want the example in a separate PR? I am adding the situation as a page in the cookbook. I can add it to this PR or a separate PR so you can do with it whatever you want.

**Pull request closed without merging**
