### PR TITLE
chore: dart-sass, glimmer/component v2

### PR DESCRIPTION
**Pull request by Techn1x**
* swap from `node-sass` to `sass` (aka dart-sass)
  * node-sass is long deprecated, and I cannot install it on my machine, so I had no choice.
* updated lockfile version (ran pnpm install with v9.5.0) + updated CI to use pnpm 9
* update to `@glimmer/component` v2 and allow it in peer deps.

Not too concerned about the sass change, since it's a build / devdependency. I ran `pnpm build` and it produced the same vendor output (see review comment)

The glimmer/component v2 update just drops ember 3.13 and makes it a v2 addon.
https://github.com/emberjs/ember.js/blob/main/packages/%40glimmer/component/CHANGELOG.md

Given the above, I think this is safe to publish as a patch or minor

---

I couldn't do the glimmer/component update without first ditching node-sass. If you feel it should be separated, feel free to do so, but I felt they are both small enough changes.

### CODE REVIEW

**Comment by Techn1x** [comment]
Can't seem to get past this error :(

```
Build Error (WebpackBundler)

ember-prism tried to import "@glimmer/component" in "ember-prism/components/code-block.js" from addon code, but "@glimmer/component" is a devDependency. You may need to move it into dependencies.
```

ember-prism looks deprecated/archived

I tried adding this to root package.json, with no luck
```
"pnpm": {
    "packageExtensions": {
      "ember-prism": {
        "dependencies": {
          "@glimmer/component": "*"
        }
      }
    }
  }
```

Any ideas? @cibernox @mkszepp

**Comment by Techn1x** [comment]
Related ember-power-calendar PR https://github.com/cibernox/ember-power-calendar/pull/527

**Comment by mkszepp** [comment]
@Techn1x thank for your PR... i will take a look today or next days, but i think we need to remove this package before we can land glimmer v2 support

**Comment by Techn1x** [comment]
Thanks! Let me know if you would like this PR to ditch the glimmer/component v2 changes for now and we can get the sass / pnpm changes merged to start with

**Comment by mkszepp** [comment]
@Techn1x the issue with node-sass i will close with this PR https://github.com/cibernox/ember-basic-dropdown/pull/938

**Comment by mkszepp** [comment]
lets see if it works after this changes... https://github.com/cibernox/ember-basic-dropdown/pull/941

**Comment by Techn1x** [comment]
I'm in the opposite timezone, I won't be at my computer for another 12 hours or so - you're welcome to change/close this PR if you like, otherwise I can remake the glimmer/component V2 update tomorrow

**Comment by mkszepp** [comment]
looks like we can't get a green ci atm, because they are using `@ember/owner` and this was introduced after 4.8 🙈... startet a discusson on discord channel... https://discord.com/channels/480462759797063690/485447409296736276/1305502264479191132

**Comment by Techn1x** [comment]
Thanks for sluething that. CI tests prevail! Sounds like they might need an ember-try config over at glimmer/component

Given the meaningful changes in this PR have been merged and/or extracted elsewhere, going to close this one

**Pull request closed without merging**
