### PR TITLE
Use ember-get-config instead of getOwner

### LINKED ISSUE #645: Type error for getOwner
When using v4 of `@types/ember__application`, we get error because getOwner now returns unknown.

```
../../node_modules/ember-basic-dropdown/addon/components/basic-dropdown.ts:318:18 - error TS2571: Object is of type 'unknown'.

318     let config = getOwner(this).resolveRegistration('config:environment');
                     ~~~~~~~~~~~~~~
Found 1 error.
```

I suggest moving to `ember-get-config`.

### PR DESCRIPTION
**Pull request by josemarluedke**
Closes #645.

### CODE REVIEW

**Comment by cibernox** [comment]
I missed this one. Let's see what CI has to say about it

**Comment by josemarluedke** [comment]
Tests are failing because we have multiple versions of embroider macros. 

I believe we need to land https://github.com/tildeio/ember-element-helper/pull/74 first to get this solved.

**Comment by josemarluedke** [comment]
Updated the PR to include upgrading to latest ember-element-helper. 

@cibernox Could you allow tests to run and merge/release once green?

**Comment by cibernox** [comment]
Thanks!

**Comment by josemarluedke** [comment]
Thanks @cibernox! Can you get this released? Will update power select after that's done.

**Comment by cibernox** [comment]
In a moment, i'm AFK right now.

**Pull request merged**
