### PR TITLE
Make sure e.target exists

### PR DESCRIPTION
**Pull request by jdurand**
Because of setTimeout I'm seeing production logs related to e.target being null

### CODE REVIEW

**Comment by cibernox** [comment]
That is surprising, since it's a timeout of 0ms. 
Can you just use an early exit (`if (!e.target) { return; }`). I find it nicer to read.

**Comment by jdurand** [comment]
Yeah I was surprised too but you know: Android; Murphy's law; etc. ;-)

**Comment by cibernox** [comment]
@jdurand i have no idea why tests are failing. Can you rebase over mastrer?

**Comment by jdurand** [comment]
There... though I doubt this will fix the CI... https://github.com/cibernox/ember-basic-dropdown/pull/306 is failing as well.

**Comment by cibernox** [comment]
@jdurand I'm going though the open PRs. Can you confirm if the bug you were trying to fix is still on the latest version?

**Comment by jdurand** [comment]
@cibernox I've been running this branch in production since July, but due to the `setTimeout` inevitably still exists.

**Comment by cibernox** [comment]
I guess that there is no harm in this, so I'll merge it once CI is green

**Pull request merged**
