### PR TITLE
Fix postion calculation - ensure that tagName are always upperCase

### PR DESCRIPTION
**Pull request by cbou**

### CODE REVIEW

**Comment by cbou** [comment]
In my app (with last Chrome) `document.body.tagName` returns "body" and not "BODY". I guess it's because of the DTD or something like that...

**Comment by cibernox** [comment]
@cbou What does DTD stands for? In the html spec `tagName` is always uppercase.

**Comment by cbou** [comment]
Please try on this page: https://charlesbourasseau.com/index.xhtml

`document.body.tagName` output `body` and not `BODY`

**Comment by cibernox** [comment]
@cbou I see. that is because your page is not HTML but XHTML, so it doesn't follow the HTML spec.

I'll merge this.

**Comment by cbou** [comment]
Yes it has nothing to do with DTD actually ;)

Thanks

**Pull request merged**
