### PR TITLE
Allow to remove/add multiple classes when transitioning out

### PR DESCRIPTION
**Pull request by thiagofesta**
I extended the `basic-dropdown/content` and added extra class and it is breaking now.

Getting this error:
```
Failed to execute 'remove' on 'DOMTokenList': The token provided ('my-class ember-basic-dropdown--transitioned-in') contains HTML space characters, which are not valid in tokens.
    at Class.animateOut (content.js:272)
```

Related to this change: https://github.com/cibernox/ember-basic-dropdown/commit/67c7257b629af14411dc7fdee4dc6c3bd2f13af5

Just updated the code to properly work with the api, break spaces and make the right call.

### CODE REVIEW

**Comment by cibernox** [comment]
Good catch, I never thought about that. Can you add a regression test for this? Is the kind of behaviour that is very easy to break inadvertently on a refactor.

**Comment by thiagofesta** [comment]
@cibernox of course, on it

**Comment by thiagofesta** [comment]
@cibernox not able to run tests, I saw you previously PR. Any updates on it?

**Comment by cibernox** [comment]
@thiagofesta yeah, CI is broken for something I don't quite get about sass. Can you just run the tests locally and check that all are green?

**Comment by thiagofesta** [comment]
@cibernox tests are not working here, how are you running them locally?

**Comment by cibernox** [comment]
Just `ember test`, as usual.

**Comment by thiagofesta** [comment]
@cibernox getting errors, like these: `Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`, i fixed using strict on the ember-cli-build.js, but it also fails in other files, do you mind taking a look, test it with a fresh checkout?

**Comment by cibernox** [comment]
@thiagofesta I suspect you're on an old version of node. Chan you check. I use 6 or bigger.

**Comment by cibernox** [comment]
@thiagofesta any update on this?

**Comment by thiagofesta** [comment]
@cibernox you were right, updated and tests started to work. I tried to write some tests, but having a hard time, they work fine when debugging at chrome, but when they run all together they are failing. I think it is mostly due to enabling animations. I will try to work a little bit more on that later today

**Comment by cibernox** [comment]
There is a couple tests that fail randomly. Run it several times.

**Comment by cibernox** [comment]
@thiagofesta I finally managed to fix travis. You should be to run tests in travis normally.

**Comment by cibernox** [comment]
@thiagofesta any update?

**Comment by thiagofesta** [comment]
@cibernox i won't have time to fix the tests, is there any change we merge this out? It seems like your travis is failing for a while:
image

https://travis-ci.org/cibernox/ember-basic-dropdown/branches

Thanks

**Comment by cibernox** [comment]
Thanks! I have no clue why tests are broken tho.

**Comment by thiagofesta** [comment]
Awesome, thanks for merging. Yeah kinda weird. Do you plan to release a version soon?

**Comment by cibernox** [comment]
@thiagofesta Done!

**Pull request merged**
